// Code generated by Kitex v0.4.4. DO NOT EDIT.

package flowservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	common "github.com/wegoteam/weflow/api/kitex_gen/common"
	flow "github.com/wegoteam/weflow/api/kitex_gen/flow"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetList(ctx context.Context, callOptions ...callopt.Option) (r []*flow.Person, err error)
	GetMap(ctx context.Context, key string, callOptions ...callopt.Option) (r map[string]int32, err error)
	GetPerson(ctx context.Context, name string, callOptions ...callopt.Option) (r *common.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFlowServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFlowServiceClient struct {
	*kClient
}

func (p *kFlowServiceClient) GetList(ctx context.Context, callOptions ...callopt.Option) (r []*flow.Person, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetList(ctx)
}

func (p *kFlowServiceClient) GetMap(ctx context.Context, key string, callOptions ...callopt.Option) (r map[string]int32, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMap(ctx, key)
}

func (p *kFlowServiceClient) GetPerson(ctx context.Context, name string, callOptions ...callopt.Option) (r *common.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPerson(ctx, name)
}
