// Code generated by Kitex v0.4.4. DO NOT EDIT.
package flowservice

import (
	server "github.com/cloudwego/kitex/server"
	flow "github.com/wegoteam/weflow/api/kitex_gen/flow"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler flow.FlowService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
