// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFlowInstTask = "flow_inst_task"

// FlowInstTask mapped from table <flow_inst_task>
type FlowInstTask struct {
	ID             int32     `gorm:"column:id;primaryKey" json:"id"`                                           // 主键
	Name           string    `gorm:"column:name;not null" json:"name"`                                         // 流程实例任务名称
	FlowInstID     string    `gorm:"column:flow_inst_id;not null" json:"flow_inst_id"`                         // 流程实例id
	FlowInstTaskID string    `gorm:"column:flow_inst_task_id;not null" json:"flow_inst_task_id"`               // 流程实例任务id
	State          int32     `gorm:"column:state;not null" json:"state"`                                       // 状态
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	CreateUser     string    `gorm:"column:create_user;not null" json:"create_user"`                           // 创建人
	UpdateTime     time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`          // 更新时间
	UpdateUser     string    `gorm:"column:update_user" json:"update_user"`                                    // 更新人
}

// TableName FlowInstTask's table name
func (*FlowInstTask) TableName() string {
	return TableNameFlowInstTask
}
