// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFlowDefNodeHandler = "flow_def_node_handler"

// FlowDefNodeHandler mapped from table <flow_def_node_handler>
type FlowDefNodeHandler struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 唯一id
	FlowDefID   string    `gorm:"column:flow_def_id;not null" json:"flow_def_id"`                           // 流程定义id
	NodeID      string    `gorm:"column:node_id;not null" json:"node_id"`                                   // 节点id
	HandlerName string    `gorm:"column:handler_name;not null" json:"handler_name"`                         // 处理人名称
	HandlerType int32     `gorm:"column:handler_type;not null;default:1" json:"handler_type"`               // 处理人类型【1：用户；2：部门；3：相对岗位；4：表单控件；5：部门岗位】
	HandlerID   string    `gorm:"column:handler_id;not null" json:"handler_id"`                             // 处理人对象id;处理对象的id，根据处理人类型区分，如果操作员id、部门id等
	HandlerSort int32     `gorm:"column:handler_sort;not null;default:1" json:"handler_sort"`               // 处理人顺序;正序排序
	ObjData     string    `gorm:"column:obj_data;not null" json:"obj_data"`                                 // 对象数据;依据处理人类型取值，相对岗位和表单控件使用该字段存json数据
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	CreateUser  string    `gorm:"column:create_user;not null" json:"create_user"`                           // 创建人
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`          // 更新时间
	UpdateUser  string    `gorm:"column:update_user" json:"update_user"`                                    // 更新人
}

// TableName FlowDefNodeHandler's table name
func (*FlowDefNodeHandler) TableName() string {
	return TableNameFlowDefNodeHandler
}
