// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFlowDefInfo = "flow_def_info"

// FlowDefInfo mapped from table <flow_def_info>
type FlowDefInfo struct {
	ID         int32     `gorm:"column:id;primaryKey" json:"id"`                                           // 主键
	Name       string    `gorm:"column:name;not null" json:"name"`                                         // 流程定义名称
	FlowDefID  string    `gorm:"column:flow_def_id;not null" json:"flow_def_id"`                           // 流程定义id
	State      int32     `gorm:"column:state;not null" json:"state"`                                       // 状态
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	CreateUser string    `gorm:"column:create_user;not null" json:"create_user"`                           // 创建人
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`          // 更新时间
	UpdateUser string    `gorm:"column:update_user" json:"update_user"`                                    // 更新人
}

// TableName FlowDefInfo's table name
func (*FlowDefInfo) TableName() string {
	return TableNameFlowDefInfo
}
