// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInstNodeTask = "inst_node_task"

// InstNodeTask mapped from table <inst_node_task>
type InstNodeTask struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 唯一id
	InstTaskID     string    `gorm:"column:inst_task_id;not null" json:"inst_task_id"`                         // 实例任务id
	NodeTaskID     string    `gorm:"column:node_task_id;not null" json:"node_task_id"`                         // 节点任务id
	NodeID         string    `gorm:"column:node_id;not null" json:"node_id"`                                   // 节点id
	ParentID       string    `gorm:"column:parent_id;not null" json:"parent_id"`                               // 父节点id
	NodeModel      int32     `gorm:"column:node_model;not null;default:1" json:"node_model"`                   // 节点模型【1：开始节点；2：审批节点；3：知会节点；4：自定义节点；5：条件节点；6：分支节点；7：汇聚节点；8：结束节点】
	NodeName       string    `gorm:"column:node_name;not null" json:"node_name"`                               // 节点名称
	ForwardMode    int32     `gorm:"column:forward_mode;not null;default:1" json:"forward_mode"`               // 进行模式【1：并行 2：串行】
	CompleteConn   int32     `gorm:"column:complete_conn;not null" json:"complete_conn"`                       // 节点完成条件;通过的人数，0表示所有人通过，节点才算完成
	PermissionMode int32     `gorm:"column:permission_mode;not null;default:1" json:"permission_mode"`         // 权限模式【1：协同 2：知会 3：审批；4：业务】
	AllowAdd       int32     `gorm:"column:allow_add;not null;default:1" json:"allow_add"`                     // 允许加签【1：不能加签；2：允许加签】
	ProcessMode    int32     `gorm:"column:process_mode;not null;default:1" json:"process_mode"`               // 处理模式【1：人工； 2：自动；3：自动转人工】
	TimeLimit      int64     `gorm:"column:time_limit;not null" json:"time_limit"`                             // 处理期限;格式：yyyymmddhhmm 可直接指定到期限的具体时间，期限支持到分钟； 0表示无期限
	ConnData       string    `gorm:"column:conn_data;not null" json:"conn_data"`                               // 条件数据;前端生成，json格式
	FormPerData    string    `gorm:"column:form_per_data;not null" json:"form_per_data"`                       // 表单权限数据;节点表单权限配置，json格式
	Status         int32     `gorm:"column:status;not null;default:1" json:"status"`                           // 任务状态【0：未开始；1：处理中；2：完成；3：回退；4：终止；5：条件验证通过；6：条件验证不通过】
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime     time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`          // 更新时间
}

// TableName InstNodeTask's table name
func (*InstNodeTask) TableName() string {
	return TableNameInstNodeTask
}
