// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInstUserTask = "inst_user_task"

// InstUserTask mapped from table <inst_user_task>
type InstUserTask struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 唯一id
	InstTaskID   string    `gorm:"column:inst_task_id;not null" json:"inst_task_id"`                         // 实例任务id
	NodeTaskID   string    `gorm:"column:node_task_id;not null" json:"node_task_id"`                         // 节点任务id
	NodeID       string    `gorm:"column:node_id;not null" json:"node_id"`                                   // 节点任务id
	UserTaskID   string    `gorm:"column:user_task_id;not null" json:"user_task_id"`                         // 处理人任务id
	Type         int32     `gorm:"column:type;not null;default:1" json:"type"`                               // 常用审批人【指定成员：1；发起人自己：2；发起人自选：3：角色：4；部门：5】主管（相对岗位）【直属主管：1；部门主管：2；连续多级主管：3；部门控件对应主管：4】其他【表单人员控件：1；部门控件：2；角色控件：3】
	Strategy     int32     `gorm:"column:strategy;not null;default:1" json:"strategy"`                       // 处理人策略【常用审批人：1；主管（相对岗位）：2；其他：3】
	NodeUserName string    `gorm:"column:node_user_name;not null" json:"node_user_name"`                     // 处理人名称
	NodeUserID   string    `gorm:"column:node_user_id;not null" json:"node_user_id"`                         // 处理人id
	Sort         int32     `gorm:"column:sort;not null;default:1" json:"sort"`                               // 处理人顺序;正序排序
	Obj          string    `gorm:"column:obj;not null" json:"obj"`                                           // 扩展字段，设计中可忽略
	Relative     string    `gorm:"column:relative;not null" json:"relative"`                                 // 相对发起人的直属主管，设计中可忽略
	Status       int32     `gorm:"column:status;not null;default:1" json:"status"`                           // 实例用户任务状态【1：处理中；2：完成（同意）；3：不通过（不同意）；4：回退；5：终止】
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`          // 更新时间
	HandleTime   time.Time `gorm:"column:handle_time;default:CURRENT_TIMESTAMP" json:"handle_time"`          // 处理时间
	OpUserID     string    `gorm:"column:op_user_id;not null" json:"op_user_id"`                             // 操作用户id
	OpUserName   string    `gorm:"column:op_user_name;not null" json:"op_user_name"`                         // 操作用户名称
	Opinion      int32     `gorm:"column:opinion;not null;default:1" json:"opinion"`                         // 任务处理意见【1：未发表；2：同意；3：不同意；4：xxx】
	OpinionDesc  string    `gorm:"column:opinion_desc;not null" json:"opinion_desc"`                         // 处理意见描述
}

// TableName InstUserTask's table name
func (*InstUserTask) TableName() string {
	return TableNameInstUserTask
}
