// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInstNodeTaskFormper = "inst_node_task_formper"

// InstNodeTaskFormper mapped from table <inst_node_task_formper>
type InstNodeTaskFormper struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 唯一id
	InstTaskID string `gorm:"column:inst_task_id;not null" json:"inst_task_id"`  // 实例任务id
	NodeTaskID string `gorm:"column:node_task_id;not null" json:"node_task_id"`  // 节点任务id
	NodeID     string `gorm:"column:node_id;not null" json:"node_id"`            // 节点id
	ElemID     string `gorm:"column:elemId;not null" json:"elemId"`              // 处理人对象id;处理对象的id，根据处理人类型区分，如果操作员id、部门id等
	ElemPID    string `gorm:"column:elemPId;not null" json:"elemPId"`            // 处理人对象id;处理对象的id，根据处理人类型区分，如果操作员id、部门id等
	Per        int32  `gorm:"column:per;not null;default:1" json:"per"`          // 处理人顺序;正序排序
}

// TableName InstNodeTaskFormper's table name
func (*InstNodeTaskFormper) TableName() string {
	return TableNameInstNodeTaskFormper
}
