// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameModelExtProp = "model_ext_prop"

// ModelExtProp mapped from table <model_ext_prop>
type ModelExtProp struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 唯一id
	ModelID    string `gorm:"column:model_id;not null" json:"model_id"`          // 模板id
	NoticeURL  string `gorm:"column:notice_url;not null" json:"notice_url"`      // 回调通知推送url
	TitleProps string `gorm:"column:title_props;not null" json:"title_props"`    // 标题配置
}

// TableName ModelExtProp's table name
func (*ModelExtProp) TableName() string {
	return TableNameModelExtProp
}
