// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameModelGroup = "model_group"

// ModelGroup mapped from table <model_group>
type ModelGroup struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 唯一id
	GroupID    string    `gorm:"column:group_id;not null" json:"group_id"`                                 // 组id
	GroupName  string    `gorm:"column:group_name;not null" json:"group_name"`                             // 组名称
	Remark     string    `gorm:"column:remark;not null" json:"remark"`                                     // 描述
	CreateUser string    `gorm:"column:create_user;not null" json:"create_user"`                           // 创建人
	UpdateUser string    `gorm:"column:update_user;not null" json:"update_user"`                           // 更新人
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`          // 更新时间
}

// TableName ModelGroup's table name
func (*ModelGroup) TableName() string {
	return TableNameModelGroup
}
