// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRoleLink = "user_role_link"

// UserRoleLink mapped from table <user_role_link>
type UserRoleLink struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 唯一id
	RoleID     string    `gorm:"column:role_id;not null" json:"role_id"`                                   // 角色id
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`                                   // 用户id
	Status     int32     `gorm:"column:status;not null;default:1" json:"status"`                           // 状态【1：未启用；2：已启用】
	Remark     string    `gorm:"column:remark;not null" json:"remark"`                                     // 描述
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`          // 更新时间
}

// TableName UserRoleLink's table name
func (*UserRoleLink) TableName() string {
	return TableNameUserRoleLink
}
