// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wego2023/weflow/pkg/model"
)

func newFlowDefNodeInfo(db *gorm.DB, opts ...gen.DOOption) flowDefNodeInfo {
	_flowDefNodeInfo := flowDefNodeInfo{}

	_flowDefNodeInfo.flowDefNodeInfoDo.UseDB(db, opts...)
	_flowDefNodeInfo.flowDefNodeInfoDo.UseModel(&model.FlowDefNodeInfo{})

	tableName := _flowDefNodeInfo.flowDefNodeInfoDo.TableName()
	_flowDefNodeInfo.ALL = field.NewAsterisk(tableName)
	_flowDefNodeInfo.ID = field.NewInt64(tableName, "id")
	_flowDefNodeInfo.FlowDefID = field.NewString(tableName, "flow_def_id")
	_flowDefNodeInfo.NodeID = field.NewString(tableName, "node_id")
	_flowDefNodeInfo.NodeType = field.NewInt32(tableName, "node_type")
	_flowDefNodeInfo.NodeName = field.NewString(tableName, "node_name")
	_flowDefNodeInfo.ForwardMode = field.NewInt32(tableName, "forward_mode")
	_flowDefNodeInfo.CompleteConn = field.NewInt32(tableName, "complete_conn")
	_flowDefNodeInfo.PermissionMode = field.NewInt32(tableName, "permission_mode")
	_flowDefNodeInfo.AllowAdd = field.NewInt32(tableName, "allow_add")
	_flowDefNodeInfo.ProcessMode = field.NewInt32(tableName, "process_mode")
	_flowDefNodeInfo.BusID = field.NewString(tableName, "bus_id")
	_flowDefNodeInfo.BusType = field.NewString(tableName, "bus_type")
	_flowDefNodeInfo.TimeLimit = field.NewInt32(tableName, "time_limit")
	_flowDefNodeInfo.ConnData = field.NewString(tableName, "conn_data")
	_flowDefNodeInfo.FormPerData = field.NewString(tableName, "form_per_data")
	_flowDefNodeInfo.Remark = field.NewString(tableName, "remark")
	_flowDefNodeInfo.CreateTime = field.NewTime(tableName, "create_time")
	_flowDefNodeInfo.CreateUser = field.NewString(tableName, "create_user")
	_flowDefNodeInfo.UpdateTime = field.NewTime(tableName, "update_time")
	_flowDefNodeInfo.UpdateUser = field.NewString(tableName, "update_user")

	_flowDefNodeInfo.fillFieldMap()

	return _flowDefNodeInfo
}

type flowDefNodeInfo struct {
	flowDefNodeInfoDo flowDefNodeInfoDo

	ALL            field.Asterisk
	ID             field.Int64  // 唯一id
	FlowDefID      field.String // 流程定义id
	NodeID         field.String // 节点id
	NodeType       field.Int32  // 节点类型;1：正常节点；2：开始节点；3：结束节点；4：汇聚节点；5：条件节点
	NodeName       field.String // 节点名称
	ForwardMode    field.Int32  // 进行模式【1：并行 2：串行】
	CompleteConn   field.Int32  // 节点完成条件;通过的人数，0表示所有人通过，节点才算完成
	PermissionMode field.Int32  // 权限模式【1：协同 2：知会 3：审批】
	AllowAdd       field.Int32  // 允许加签【1：不能加签；2：允许加签】
	ProcessMode    field.Int32  // 处理模式【1：人工； 2：自动】
	BusID          field.String // 业务id
	BusType        field.String // 业务类型
	TimeLimit      field.Int32  // 处理期限时长;单位秒，0表示无期限；
	ConnData       field.String // 条件表达式;条件节点才有条件表达式
	FormPerData    field.String // 表单权限数据;节点表单权限配置，json格式
	Remark         field.String // 节点描述
	CreateTime     field.Time   // 创建时间
	CreateUser     field.String // 创建人
	UpdateTime     field.Time   // 更新时间
	UpdateUser     field.String // 更新人

	fieldMap map[string]field.Expr
}

func (f flowDefNodeInfo) Table(newTableName string) *flowDefNodeInfo {
	f.flowDefNodeInfoDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f flowDefNodeInfo) As(alias string) *flowDefNodeInfo {
	f.flowDefNodeInfoDo.DO = *(f.flowDefNodeInfoDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *flowDefNodeInfo) updateTableName(table string) *flowDefNodeInfo {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.FlowDefID = field.NewString(table, "flow_def_id")
	f.NodeID = field.NewString(table, "node_id")
	f.NodeType = field.NewInt32(table, "node_type")
	f.NodeName = field.NewString(table, "node_name")
	f.ForwardMode = field.NewInt32(table, "forward_mode")
	f.CompleteConn = field.NewInt32(table, "complete_conn")
	f.PermissionMode = field.NewInt32(table, "permission_mode")
	f.AllowAdd = field.NewInt32(table, "allow_add")
	f.ProcessMode = field.NewInt32(table, "process_mode")
	f.BusID = field.NewString(table, "bus_id")
	f.BusType = field.NewString(table, "bus_type")
	f.TimeLimit = field.NewInt32(table, "time_limit")
	f.ConnData = field.NewString(table, "conn_data")
	f.FormPerData = field.NewString(table, "form_per_data")
	f.Remark = field.NewString(table, "remark")
	f.CreateTime = field.NewTime(table, "create_time")
	f.CreateUser = field.NewString(table, "create_user")
	f.UpdateTime = field.NewTime(table, "update_time")
	f.UpdateUser = field.NewString(table, "update_user")

	f.fillFieldMap()

	return f
}

func (f *flowDefNodeInfo) WithContext(ctx context.Context) *flowDefNodeInfoDo {
	return f.flowDefNodeInfoDo.WithContext(ctx)
}

func (f flowDefNodeInfo) TableName() string { return f.flowDefNodeInfoDo.TableName() }

func (f flowDefNodeInfo) Alias() string { return f.flowDefNodeInfoDo.Alias() }

func (f *flowDefNodeInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *flowDefNodeInfo) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 20)
	f.fieldMap["id"] = f.ID
	f.fieldMap["flow_def_id"] = f.FlowDefID
	f.fieldMap["node_id"] = f.NodeID
	f.fieldMap["node_type"] = f.NodeType
	f.fieldMap["node_name"] = f.NodeName
	f.fieldMap["forward_mode"] = f.ForwardMode
	f.fieldMap["complete_conn"] = f.CompleteConn
	f.fieldMap["permission_mode"] = f.PermissionMode
	f.fieldMap["allow_add"] = f.AllowAdd
	f.fieldMap["process_mode"] = f.ProcessMode
	f.fieldMap["bus_id"] = f.BusID
	f.fieldMap["bus_type"] = f.BusType
	f.fieldMap["time_limit"] = f.TimeLimit
	f.fieldMap["conn_data"] = f.ConnData
	f.fieldMap["form_per_data"] = f.FormPerData
	f.fieldMap["remark"] = f.Remark
	f.fieldMap["create_time"] = f.CreateTime
	f.fieldMap["create_user"] = f.CreateUser
	f.fieldMap["update_time"] = f.UpdateTime
	f.fieldMap["update_user"] = f.UpdateUser
}

func (f flowDefNodeInfo) clone(db *gorm.DB) flowDefNodeInfo {
	f.flowDefNodeInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f flowDefNodeInfo) replaceDB(db *gorm.DB) flowDefNodeInfo {
	f.flowDefNodeInfoDo.ReplaceDB(db)
	return f
}

type flowDefNodeInfoDo struct{ gen.DO }

func (f flowDefNodeInfoDo) Debug() *flowDefNodeInfoDo {
	return f.withDO(f.DO.Debug())
}

func (f flowDefNodeInfoDo) WithContext(ctx context.Context) *flowDefNodeInfoDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f flowDefNodeInfoDo) ReadDB() *flowDefNodeInfoDo {
	return f.Clauses(dbresolver.Read)
}

func (f flowDefNodeInfoDo) WriteDB() *flowDefNodeInfoDo {
	return f.Clauses(dbresolver.Write)
}

func (f flowDefNodeInfoDo) Session(config *gorm.Session) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Session(config))
}

func (f flowDefNodeInfoDo) Clauses(conds ...clause.Expression) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f flowDefNodeInfoDo) Returning(value interface{}, columns ...string) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f flowDefNodeInfoDo) Not(conds ...gen.Condition) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f flowDefNodeInfoDo) Or(conds ...gen.Condition) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f flowDefNodeInfoDo) Select(conds ...field.Expr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f flowDefNodeInfoDo) Where(conds ...gen.Condition) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f flowDefNodeInfoDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *flowDefNodeInfoDo {
	return f.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (f flowDefNodeInfoDo) Order(conds ...field.Expr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f flowDefNodeInfoDo) Distinct(cols ...field.Expr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f flowDefNodeInfoDo) Omit(cols ...field.Expr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f flowDefNodeInfoDo) Join(table schema.Tabler, on ...field.Expr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f flowDefNodeInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f flowDefNodeInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f flowDefNodeInfoDo) Group(cols ...field.Expr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f flowDefNodeInfoDo) Having(conds ...gen.Condition) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f flowDefNodeInfoDo) Limit(limit int) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f flowDefNodeInfoDo) Offset(offset int) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f flowDefNodeInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f flowDefNodeInfoDo) Unscoped() *flowDefNodeInfoDo {
	return f.withDO(f.DO.Unscoped())
}

func (f flowDefNodeInfoDo) Create(values ...*model.FlowDefNodeInfo) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f flowDefNodeInfoDo) CreateInBatches(values []*model.FlowDefNodeInfo, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f flowDefNodeInfoDo) Save(values ...*model.FlowDefNodeInfo) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f flowDefNodeInfoDo) First() (*model.FlowDefNodeInfo, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowDefNodeInfo), nil
	}
}

func (f flowDefNodeInfoDo) Take() (*model.FlowDefNodeInfo, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowDefNodeInfo), nil
	}
}

func (f flowDefNodeInfoDo) Last() (*model.FlowDefNodeInfo, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowDefNodeInfo), nil
	}
}

func (f flowDefNodeInfoDo) Find() ([]*model.FlowDefNodeInfo, error) {
	result, err := f.DO.Find()
	return result.([]*model.FlowDefNodeInfo), err
}

func (f flowDefNodeInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FlowDefNodeInfo, err error) {
	buf := make([]*model.FlowDefNodeInfo, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f flowDefNodeInfoDo) FindInBatches(result *[]*model.FlowDefNodeInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f flowDefNodeInfoDo) Attrs(attrs ...field.AssignExpr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f flowDefNodeInfoDo) Assign(attrs ...field.AssignExpr) *flowDefNodeInfoDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f flowDefNodeInfoDo) Joins(fields ...field.RelationField) *flowDefNodeInfoDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f flowDefNodeInfoDo) Preload(fields ...field.RelationField) *flowDefNodeInfoDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f flowDefNodeInfoDo) FirstOrInit() (*model.FlowDefNodeInfo, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowDefNodeInfo), nil
	}
}

func (f flowDefNodeInfoDo) FirstOrCreate() (*model.FlowDefNodeInfo, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowDefNodeInfo), nil
	}
}

func (f flowDefNodeInfoDo) FindByPage(offset int, limit int) (result []*model.FlowDefNodeInfo, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f flowDefNodeInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f flowDefNodeInfoDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f flowDefNodeInfoDo) Delete(models ...*model.FlowDefNodeInfo) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *flowDefNodeInfoDo) withDO(do gen.Dao) *flowDefNodeInfoDo {
	f.DO = *do.(*gen.DO)
	return f
}
