// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/wegoteam/weflow/pkg/model"
)

func newInstNodeTask(db *gorm.DB, opts ...gen.DOOption) instNodeTask {
	_instNodeTask := instNodeTask{}

	_instNodeTask.instNodeTaskDo.UseDB(db, opts...)
	_instNodeTask.instNodeTaskDo.UseModel(&model.InstNodeTask{})

	tableName := _instNodeTask.instNodeTaskDo.TableName()
	_instNodeTask.ALL = field.NewAsterisk(tableName)
	_instNodeTask.ID = field.NewInt64(tableName, "id")
	_instNodeTask.InstTaskID = field.NewString(tableName, "inst_task_id")
	_instNodeTask.NodeTaskID = field.NewString(tableName, "node_task_id")
	_instNodeTask.NodeID = field.NewString(tableName, "node_id")
	_instNodeTask.ParentID = field.NewString(tableName, "parent_id")
	_instNodeTask.NodeModel = field.NewInt32(tableName, "node_model")
	_instNodeTask.NodeName = field.NewString(tableName, "node_name")
	_instNodeTask.ApproveType = field.NewInt32(tableName, "approve_type")
	_instNodeTask.NoneHandler = field.NewInt32(tableName, "none_handler")
	_instNodeTask.AppointHandler = field.NewString(tableName, "appoint_handler")
	_instNodeTask.HandleMode = field.NewInt32(tableName, "handle_mode")
	_instNodeTask.FinishMode = field.NewInt32(tableName, "finish_mode")
	_instNodeTask.BranchMode = field.NewInt32(tableName, "branch_mode")
	_instNodeTask.DefaultBranch = field.NewInt32(tableName, "default_branch")
	_instNodeTask.BranchLevel = field.NewInt32(tableName, "branch_level")
	_instNodeTask.ConditionGroup = field.NewString(tableName, "condition_group")
	_instNodeTask.ConditionExpr = field.NewString(tableName, "condition_expr")
	_instNodeTask.Remark = field.NewString(tableName, "remark")
	_instNodeTask.Status = field.NewInt32(tableName, "status")
	_instNodeTask.CreateTime = field.NewTime(tableName, "create_time")
	_instNodeTask.UpdateTime = field.NewTime(tableName, "update_time")

	_instNodeTask.fillFieldMap()

	return _instNodeTask
}

type instNodeTask struct {
	instNodeTaskDo instNodeTaskDo

	ALL            field.Asterisk
	ID             field.Int64  // 唯一id
	InstTaskID     field.String // 实例任务id
	NodeTaskID     field.String // 节点任务id
	NodeID         field.String // 节点id
	ParentID       field.String // 父节点id
	NodeModel      field.Int32  // 节点模型【1：开始节点；2：审批节点；3：办理节点；4：抄送节点；5：自定义节点；6：条件节点；7：分支节点；8：汇聚节点；9：结束节点】
	NodeName       field.String // 节点名称
	ApproveType    field.Int32  // 审批类型【人工审批：1；自动通过：2；自动拒绝】默认人工审批1
	NoneHandler    field.Int32  // 审批人为空时【自动通过：1；自动转交管理员：2；指定审批人：3】默认自动通过1
	AppointHandler field.String // 审批人为空时指定审批人ID
	HandleMode     field.Int32  // 审批方式【依次审批：1、会签（需要完成人数的审批人同意或拒绝才可完成节点）：2、或签（其中一名审批人同意或拒绝即可）：3】默认会签2
	FinishMode     field.Int32  // 完成人数：依次审批默认0所有人不可选人，会签默认0所有人（可选人大于0），或签默认1一个人（可选人大于0）
	BranchMode     field.Int32  // 分支执行方式【单分支：1；多分支：2】默认多分支2
	DefaultBranch  field.Int32  // 单分支处理需要默认分支，在条件优先级无法处理时候执行默认分支，取值分支下标
	BranchLevel    field.Int32  // 优先级，分支执行方式为多分支处理方式无优先级应为0
	ConditionGroup field.String // 条件组前端描述展示条件组
	ConditionExpr  field.String // 条件组解析后的表达式
	Remark         field.String // 节点描述
	Status         field.Int32  // 任务状态【1：未开始；2：处理中；3：完成；4：回退；5：终止；6：不通过】
	CreateTime     field.Time   // 创建时间
	UpdateTime     field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (i instNodeTask) Table(newTableName string) *instNodeTask {
	i.instNodeTaskDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i instNodeTask) As(alias string) *instNodeTask {
	i.instNodeTaskDo.DO = *(i.instNodeTaskDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *instNodeTask) updateTableName(table string) *instNodeTask {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.InstTaskID = field.NewString(table, "inst_task_id")
	i.NodeTaskID = field.NewString(table, "node_task_id")
	i.NodeID = field.NewString(table, "node_id")
	i.ParentID = field.NewString(table, "parent_id")
	i.NodeModel = field.NewInt32(table, "node_model")
	i.NodeName = field.NewString(table, "node_name")
	i.ApproveType = field.NewInt32(table, "approve_type")
	i.NoneHandler = field.NewInt32(table, "none_handler")
	i.AppointHandler = field.NewString(table, "appoint_handler")
	i.HandleMode = field.NewInt32(table, "handle_mode")
	i.FinishMode = field.NewInt32(table, "finish_mode")
	i.BranchMode = field.NewInt32(table, "branch_mode")
	i.DefaultBranch = field.NewInt32(table, "default_branch")
	i.BranchLevel = field.NewInt32(table, "branch_level")
	i.ConditionGroup = field.NewString(table, "condition_group")
	i.ConditionExpr = field.NewString(table, "condition_expr")
	i.Remark = field.NewString(table, "remark")
	i.Status = field.NewInt32(table, "status")
	i.CreateTime = field.NewTime(table, "create_time")
	i.UpdateTime = field.NewTime(table, "update_time")

	i.fillFieldMap()

	return i
}

func (i *instNodeTask) WithContext(ctx context.Context) *instNodeTaskDo {
	return i.instNodeTaskDo.WithContext(ctx)
}

func (i instNodeTask) TableName() string { return i.instNodeTaskDo.TableName() }

func (i instNodeTask) Alias() string { return i.instNodeTaskDo.Alias() }

func (i *instNodeTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *instNodeTask) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 21)
	i.fieldMap["id"] = i.ID
	i.fieldMap["inst_task_id"] = i.InstTaskID
	i.fieldMap["node_task_id"] = i.NodeTaskID
	i.fieldMap["node_id"] = i.NodeID
	i.fieldMap["parent_id"] = i.ParentID
	i.fieldMap["node_model"] = i.NodeModel
	i.fieldMap["node_name"] = i.NodeName
	i.fieldMap["approve_type"] = i.ApproveType
	i.fieldMap["none_handler"] = i.NoneHandler
	i.fieldMap["appoint_handler"] = i.AppointHandler
	i.fieldMap["handle_mode"] = i.HandleMode
	i.fieldMap["finish_mode"] = i.FinishMode
	i.fieldMap["branch_mode"] = i.BranchMode
	i.fieldMap["default_branch"] = i.DefaultBranch
	i.fieldMap["branch_level"] = i.BranchLevel
	i.fieldMap["condition_group"] = i.ConditionGroup
	i.fieldMap["condition_expr"] = i.ConditionExpr
	i.fieldMap["remark"] = i.Remark
	i.fieldMap["status"] = i.Status
	i.fieldMap["create_time"] = i.CreateTime
	i.fieldMap["update_time"] = i.UpdateTime
}

func (i instNodeTask) clone(db *gorm.DB) instNodeTask {
	i.instNodeTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i instNodeTask) replaceDB(db *gorm.DB) instNodeTask {
	i.instNodeTaskDo.ReplaceDB(db)
	return i
}

type instNodeTaskDo struct{ gen.DO }

func (i instNodeTaskDo) Debug() *instNodeTaskDo {
	return i.withDO(i.DO.Debug())
}

func (i instNodeTaskDo) WithContext(ctx context.Context) *instNodeTaskDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i instNodeTaskDo) ReadDB() *instNodeTaskDo {
	return i.Clauses(dbresolver.Read)
}

func (i instNodeTaskDo) WriteDB() *instNodeTaskDo {
	return i.Clauses(dbresolver.Write)
}

func (i instNodeTaskDo) Session(config *gorm.Session) *instNodeTaskDo {
	return i.withDO(i.DO.Session(config))
}

func (i instNodeTaskDo) Clauses(conds ...clause.Expression) *instNodeTaskDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i instNodeTaskDo) Returning(value interface{}, columns ...string) *instNodeTaskDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i instNodeTaskDo) Not(conds ...gen.Condition) *instNodeTaskDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i instNodeTaskDo) Or(conds ...gen.Condition) *instNodeTaskDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i instNodeTaskDo) Select(conds ...field.Expr) *instNodeTaskDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i instNodeTaskDo) Where(conds ...gen.Condition) *instNodeTaskDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i instNodeTaskDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *instNodeTaskDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i instNodeTaskDo) Order(conds ...field.Expr) *instNodeTaskDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i instNodeTaskDo) Distinct(cols ...field.Expr) *instNodeTaskDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i instNodeTaskDo) Omit(cols ...field.Expr) *instNodeTaskDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i instNodeTaskDo) Join(table schema.Tabler, on ...field.Expr) *instNodeTaskDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i instNodeTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *instNodeTaskDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i instNodeTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *instNodeTaskDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i instNodeTaskDo) Group(cols ...field.Expr) *instNodeTaskDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i instNodeTaskDo) Having(conds ...gen.Condition) *instNodeTaskDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i instNodeTaskDo) Limit(limit int) *instNodeTaskDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i instNodeTaskDo) Offset(offset int) *instNodeTaskDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i instNodeTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *instNodeTaskDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i instNodeTaskDo) Unscoped() *instNodeTaskDo {
	return i.withDO(i.DO.Unscoped())
}

func (i instNodeTaskDo) Create(values ...*model.InstNodeTask) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i instNodeTaskDo) CreateInBatches(values []*model.InstNodeTask, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i instNodeTaskDo) Save(values ...*model.InstNodeTask) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i instNodeTaskDo) First() (*model.InstNodeTask, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstNodeTask), nil
	}
}

func (i instNodeTaskDo) Take() (*model.InstNodeTask, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstNodeTask), nil
	}
}

func (i instNodeTaskDo) Last() (*model.InstNodeTask, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstNodeTask), nil
	}
}

func (i instNodeTaskDo) Find() ([]*model.InstNodeTask, error) {
	result, err := i.DO.Find()
	return result.([]*model.InstNodeTask), err
}

func (i instNodeTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InstNodeTask, err error) {
	buf := make([]*model.InstNodeTask, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i instNodeTaskDo) FindInBatches(result *[]*model.InstNodeTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i instNodeTaskDo) Attrs(attrs ...field.AssignExpr) *instNodeTaskDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i instNodeTaskDo) Assign(attrs ...field.AssignExpr) *instNodeTaskDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i instNodeTaskDo) Joins(fields ...field.RelationField) *instNodeTaskDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i instNodeTaskDo) Preload(fields ...field.RelationField) *instNodeTaskDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i instNodeTaskDo) FirstOrInit() (*model.InstNodeTask, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstNodeTask), nil
	}
}

func (i instNodeTaskDo) FirstOrCreate() (*model.InstNodeTask, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstNodeTask), nil
	}
}

func (i instNodeTaskDo) FindByPage(offset int, limit int) (result []*model.InstNodeTask, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i instNodeTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i instNodeTaskDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i instNodeTaskDo) Delete(models ...*model.InstNodeTask) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *instNodeTaskDo) withDO(do gen.Dao) *instNodeTaskDo {
	i.DO = *do.(*gen.DO)
	return i
}
