// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/wegoteam/weflow/pkg/model"
)

func newUserRoleLink(db *gorm.DB, opts ...gen.DOOption) userRoleLink {
	_userRoleLink := userRoleLink{}

	_userRoleLink.userRoleLinkDo.UseDB(db, opts...)
	_userRoleLink.userRoleLinkDo.UseModel(&model.UserRoleLink{})

	tableName := _userRoleLink.userRoleLinkDo.TableName()
	_userRoleLink.ALL = field.NewAsterisk(tableName)
	_userRoleLink.ID = field.NewInt64(tableName, "id")
	_userRoleLink.RoleID = field.NewString(tableName, "role_id")
	_userRoleLink.UserID = field.NewString(tableName, "user_id")
	_userRoleLink.Status = field.NewInt32(tableName, "status")
	_userRoleLink.Remark = field.NewString(tableName, "remark")
	_userRoleLink.CreateTime = field.NewTime(tableName, "create_time")
	_userRoleLink.UpdateTime = field.NewTime(tableName, "update_time")

	_userRoleLink.fillFieldMap()

	return _userRoleLink
}

type userRoleLink struct {
	userRoleLinkDo userRoleLinkDo

	ALL        field.Asterisk
	ID         field.Int64  // 唯一id
	RoleID     field.String // 角色id
	UserID     field.String // 用户id
	Status     field.Int32  // 状态【1：未启用；2：已启用】
	Remark     field.String // 描述
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (u userRoleLink) Table(newTableName string) *userRoleLink {
	u.userRoleLinkDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userRoleLink) As(alias string) *userRoleLink {
	u.userRoleLinkDo.DO = *(u.userRoleLinkDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userRoleLink) updateTableName(table string) *userRoleLink {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.RoleID = field.NewString(table, "role_id")
	u.UserID = field.NewString(table, "user_id")
	u.Status = field.NewInt32(table, "status")
	u.Remark = field.NewString(table, "remark")
	u.CreateTime = field.NewTime(table, "create_time")
	u.UpdateTime = field.NewTime(table, "update_time")

	u.fillFieldMap()

	return u
}

func (u *userRoleLink) WithContext(ctx context.Context) *userRoleLinkDo {
	return u.userRoleLinkDo.WithContext(ctx)
}

func (u userRoleLink) TableName() string { return u.userRoleLinkDo.TableName() }

func (u userRoleLink) Alias() string { return u.userRoleLinkDo.Alias() }

func (u *userRoleLink) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userRoleLink) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["role_id"] = u.RoleID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["status"] = u.Status
	u.fieldMap["remark"] = u.Remark
	u.fieldMap["create_time"] = u.CreateTime
	u.fieldMap["update_time"] = u.UpdateTime
}

func (u userRoleLink) clone(db *gorm.DB) userRoleLink {
	u.userRoleLinkDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userRoleLink) replaceDB(db *gorm.DB) userRoleLink {
	u.userRoleLinkDo.ReplaceDB(db)
	return u
}

type userRoleLinkDo struct{ gen.DO }

func (u userRoleLinkDo) Debug() *userRoleLinkDo {
	return u.withDO(u.DO.Debug())
}

func (u userRoleLinkDo) WithContext(ctx context.Context) *userRoleLinkDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userRoleLinkDo) ReadDB() *userRoleLinkDo {
	return u.Clauses(dbresolver.Read)
}

func (u userRoleLinkDo) WriteDB() *userRoleLinkDo {
	return u.Clauses(dbresolver.Write)
}

func (u userRoleLinkDo) Session(config *gorm.Session) *userRoleLinkDo {
	return u.withDO(u.DO.Session(config))
}

func (u userRoleLinkDo) Clauses(conds ...clause.Expression) *userRoleLinkDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userRoleLinkDo) Returning(value interface{}, columns ...string) *userRoleLinkDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userRoleLinkDo) Not(conds ...gen.Condition) *userRoleLinkDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userRoleLinkDo) Or(conds ...gen.Condition) *userRoleLinkDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userRoleLinkDo) Select(conds ...field.Expr) *userRoleLinkDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userRoleLinkDo) Where(conds ...gen.Condition) *userRoleLinkDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userRoleLinkDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *userRoleLinkDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u userRoleLinkDo) Order(conds ...field.Expr) *userRoleLinkDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userRoleLinkDo) Distinct(cols ...field.Expr) *userRoleLinkDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userRoleLinkDo) Omit(cols ...field.Expr) *userRoleLinkDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userRoleLinkDo) Join(table schema.Tabler, on ...field.Expr) *userRoleLinkDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userRoleLinkDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userRoleLinkDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userRoleLinkDo) RightJoin(table schema.Tabler, on ...field.Expr) *userRoleLinkDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userRoleLinkDo) Group(cols ...field.Expr) *userRoleLinkDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userRoleLinkDo) Having(conds ...gen.Condition) *userRoleLinkDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userRoleLinkDo) Limit(limit int) *userRoleLinkDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userRoleLinkDo) Offset(offset int) *userRoleLinkDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userRoleLinkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userRoleLinkDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userRoleLinkDo) Unscoped() *userRoleLinkDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userRoleLinkDo) Create(values ...*model.UserRoleLink) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userRoleLinkDo) CreateInBatches(values []*model.UserRoleLink, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userRoleLinkDo) Save(values ...*model.UserRoleLink) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userRoleLinkDo) First() (*model.UserRoleLink, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRoleLink), nil
	}
}

func (u userRoleLinkDo) Take() (*model.UserRoleLink, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRoleLink), nil
	}
}

func (u userRoleLinkDo) Last() (*model.UserRoleLink, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRoleLink), nil
	}
}

func (u userRoleLinkDo) Find() ([]*model.UserRoleLink, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserRoleLink), err
}

func (u userRoleLinkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserRoleLink, err error) {
	buf := make([]*model.UserRoleLink, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userRoleLinkDo) FindInBatches(result *[]*model.UserRoleLink, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userRoleLinkDo) Attrs(attrs ...field.AssignExpr) *userRoleLinkDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userRoleLinkDo) Assign(attrs ...field.AssignExpr) *userRoleLinkDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userRoleLinkDo) Joins(fields ...field.RelationField) *userRoleLinkDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userRoleLinkDo) Preload(fields ...field.RelationField) *userRoleLinkDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userRoleLinkDo) FirstOrInit() (*model.UserRoleLink, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRoleLink), nil
	}
}

func (u userRoleLinkDo) FirstOrCreate() (*model.UserRoleLink, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRoleLink), nil
	}
}

func (u userRoleLinkDo) FindByPage(offset int, limit int) (result []*model.UserRoleLink, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userRoleLinkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userRoleLinkDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userRoleLinkDo) Delete(models ...*model.UserRoleLink) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userRoleLinkDo) withDO(do gen.Dao) *userRoleLinkDo {
	u.DO = *do.(*gen.DO)
	return u
}
