// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	commRouter "github.com/wegoteam/weflow/internal/biz/router/comm"
	flowRouter "github.com/wegoteam/weflow/internal/biz/router/flow"
	insttaskRouter "github.com/wegoteam/weflow/internal/biz/router/insttask"
	modelRouter "github.com/wegoteam/weflow/internal/biz/router/model"
	usertaskRouter "github.com/wegoteam/weflow/internal/biz/router/usertask"
)

// GeneratedRegister
// @Description: 注册路由
// @param: hertz
func GeneratedRegister(hertz *server.Hertz) {
	//注册公共路由
	commRouter.Register(hertz)
	//注册流程路由
	flowRouter.Register(hertz)
	//注册模板路由
	modelRouter.Register(hertz)
	//注册用户任务路由
	usertaskRouter.Register(hertz)
	//注册实例任务路由
	insttaskRouter.Register(hertz)
}
